**N**<br /><br />
**[NAL](https://github.com/opennars/opennars/wiki/Non-Axiomatic-Logic-(NAL),-Logic-behind-OpenNARS)** - Non-Axiomatic Logic core logic used in OpenNARS <br />
**[Narsese](https://github.com/opennars/opennars/wiki/Narsese-Grammar,-Language-of-OpenNARS)** - Grammar Statement used for communication with OpenNARS control mechanism<br /><br />

**P**<br /><br/>
Predicate term - term used to the right of [copula] (https://github.com/opennars/opennars/wiki/Narsese-Grammar,-Language-of-OpenNARS)


**S**<br /><br/>
Subject term - term used t
o the left of [copula] (https://github.com/opennars/opennars/wiki/Narsese-Grammar,-Language-of-OpenNARS)

**T**<br /><br/>
**Term** - simplest atomic structure within a grammar statement, basically a string of letters in alphabet<br /><br/>
**Transitive Closure** - given that inheritance (-->) relation is transitive, that is if A-->B and B-->C then A-->C, closure is a set of statements generated by closure-algorithm using transitivity property  <br /><br />
